#%RAML 0.8

title: Tickets booking API
version: v1

schemas:
  - event_get: !include schemas/event_get.json
  - event_post: !include schemas/event_post.json
  - ticket_get: !include schemas/ticket_get.json
  - ticket_post: !include schemas/ticket_post.json
  - ticket_patch: !include schemas/ticket_patch.json
  - ticket_list_get: !include schemas/ticket_list_get.json
  - error: !include schemas/error.json

/events:
  get:
    description: Retrieve events list
    responses:
      200:
        body:
          application/json:
  post:
    description: Creates new event
    body:
      application/json:
        schema: event_post        
    responses:
      201:
        body:
          application/json:
            schema: event_get
      422:
        body:
          application/json:
            schema: error
  /{eventId}:
    get:
      description: Retrieve scpecific event details
      responses:
        200:          
          body:
            application/json:
              schema: event_get
    put:    
      description: Update event properties
      body:
        application/json:
          schema: event_get
      responses:
        200:          
          body:
            application/json:
              schema: event_get
        422:
          body:
            application/json:
              schema: error
    /tickets:
      get:
        description: Retrieve a list of tickets for specified eventId
        responses:
          200:
            body:
              application/json:
                schema: ticket_list_get
      post:
        description: Create tickets amount  for event
        body:        
          application/json:
            schema: ticket_post
        responses:
          201:          
            body:
              application/json:
                schema: ticket_list_get


/tickets:
  /{ticketId}:
    get:
      description: Retrieve ticket information
      responses:
        200:
          body:
            application/json:
              schema: ticket_get
    patch:
      description: Modify ticket status
      body:
        application/json:
          schema: ticket_patch
      responses:
        200:          
          body:
            application/json:
              schema: ticket_get
    delete:
      description: Delete specified ticket
      responses:
        204:

/users:
  /{userId}/tickets:
    get:
      description: Retrieve all tickets for specified userId
      responses:
        200:          
          body:
            application/json:
              schema: ticket_list_get